name: Custom version bump
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare
        run: |
          npm install @changesets/cli
          npx changeset init
      - name: Add Changes
        run: |
          if ! npx changeset add; then
            echo "No changes detected"
            exit 0
          fi
      - name: Precommit
        run: |
          if ! npx changeset precommit; then
            echo "No changes to commit"
            exit 0
          fi
      - name: Publish
        run: |
          npx changesets publish
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACTION }}
