name: Custom version bump
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: changesets/action@v1
        with:
          github-token: ${{ secrets.TOKEN_ACTION }}
          commit-message: 'chore(release): {version}'
