name: Changesets Version Bump
on:
  push:
    branches:
      - main
jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Changesets
        run: |
          npx changeset init
          npx changeset precommit
          npx changesets publish
          git push
