name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - main-test

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use NodeJS 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Version and publish
      env:
        GH_TOKEN: ${{ secrets.TOKEN_ACTION }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

        npx lerna version --conventional-commits --yes
        npx lerna publish from-git --yes
